[workspace]
members = ["mimc", "mimc-fast", "darkforest"]

# force release mode for dev in case people dont use --release
[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false
